version: '3'
services:
  app:
    build:
      context: C:\Users\visok\Documents\go\api_sotr
      dockerfile: Dockerfile
    container_name: app
    ports:
      - '8000:8000'
    env_file:
      - ./.env
